import { GoogleGenerativeAI } from '@google/generative-ai';
import { GenerationRequest, GeneratedComponent } from '@/types/generated-component';
import { SYSTEM_PROMPT, generateUserPrompt } from './prompts';
import { parseGeneratedCode } from './parser';

export async function generateComponent(request: GenerationRequest): Promise<GeneratedComponent> {
    const { sectionData } = request;

    if (!process.env.GEMINI_API_KEY) {
        throw new Error("GEMINI_API_KEY is missing. Please add it to your .env.local file.");
    }

    return generateWithGemini(request);
}

async function generateWithGemini(request: GenerationRequest): Promise<GeneratedComponent> {
    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
    const { sectionData, customPrompt } = request;

    // Updated to use Gemini 2.5 Flash on API v1 as requested
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" }, { apiVersion: 'v1' });

    const userPrompt = customPrompt || generateUserPrompt(sectionData.type, sectionData.html, sectionData.images);

    // Construct prompt parts
    const promptParts: any[] = [
        SYSTEM_PROMPT,
        "\n\nUser Task:\n",
        userPrompt
    ];

    if (sectionData.screenshot) {
        promptParts.push({
            inlineData: {
                data: sectionData.screenshot,
                mimeType: "image/jpeg"
            }
        });
    }

    try {
        const result = await model.generateContent(promptParts);
        const response = await result.response;
        const text = response.text();

        const code = parseGeneratedCode(text);

        return {
            id: sectionData.id,
            name: `${sectionData.type.charAt(0).toUpperCase() + sectionData.type.slice(1)}Component`,
            code,
            description: "Generated by Gemini 2.5 Flash",
        };
    } catch (error) {
        console.error("Gemini Generation Error:", error);
        throw new Error("Failed to generate component with Gemini.");
    }
}
